// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restrichef.Api.Infrastructure.Data;

#nullable disable

namespace Restrichef.Api.Migrations
{
    [DbContext(typeof(RestrichefDbContext))]
    [Migration("20260131122027_AjusteSeedERelacionamentos")]
    partial class AjusteSeedERelacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IngredienteRestricaoAlimentar", b =>
                {
                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RestricoesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IngredienteId", "RestricoesId");

                    b.HasIndex("RestricoesId");

                    b.ToTable("IngredienteRestricoes", (string)null);
                });

            modelBuilder.Entity("PerfilAlimentarRestricaoAlimentar", b =>
                {
                    b.Property<Guid>("PerfilAlimentarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RestricoesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PerfilAlimentarId", "RestricoesId");

                    b.HasIndex("RestricoesId");

                    b.ToTable("PerfilAlimentarRestricoes", (string)null);
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.IngredienteReceita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReceitaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("IngredientesReceita");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PassoPreparo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceitaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("PassosPreparo");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PerfilAlimentar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PerfisAlimentares");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porcoes")
                        .HasColumnType("int");

                    b.Property<int>("TempoMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.RestricaoAlimentar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RestricoesAlimentares");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IngredienteRestricaoAlimentar", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restrichef.Api.Domain.Entities.RestricaoAlimentar", null)
                        .WithMany()
                        .HasForeignKey("RestricoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfilAlimentarRestricaoAlimentar", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.PerfilAlimentar", null)
                        .WithMany()
                        .HasForeignKey("PerfilAlimentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restrichef.Api.Domain.Entities.RestricaoAlimentar", null)
                        .WithMany()
                        .HasForeignKey("RestricoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.IngredienteReceita", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restrichef.Api.Domain.Entities.Receita", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PassoPreparo", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.Receita", null)
                        .WithMany("PassosPreparo")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PerfilAlimentar", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.User", null)
                        .WithOne("PerfilAlimentar")
                        .HasForeignKey("Restrichef.Api.Domain.Entities.PerfilAlimentar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Receita", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.Ingrediente", null)
                        .WithMany("Receitas")
                        .HasForeignKey("IngredienteId");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Ingrediente", b =>
                {
                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Receita", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("PassosPreparo");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("PerfilAlimentar")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
