// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restrichef.Api.Infrastructure.Data;

#nullable disable

namespace Restrichef.Api.Migrations
{
    [DbContext(typeof(RestrichefDbContext))]
    [Migration("20260126220356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PerfilAlimentar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PerfisAlimentares");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.RestricaoAlimentar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PerfilAlimentarId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PerfilAlimentarId");

                    b.ToTable("RestricoesAlimentares");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PerfilAlimentar", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.User", null)
                        .WithOne("PerfilAlimentar")
                        .HasForeignKey("Restrichef.Api.Domain.Entities.PerfilAlimentar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.RestricaoAlimentar", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.PerfilAlimentar", null)
                        .WithMany("Restricoes")
                        .HasForeignKey("PerfilAlimentarId");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PerfilAlimentar", b =>
                {
                    b.Navigation("Restricoes");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("PerfilAlimentar")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
