// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restrichef.Api.Infrastructure.Data;

#nullable disable

namespace Restrichef.Api.Migrations
{
    [DbContext(typeof(RestrichefDbContext))]
    [Migration("20260129201531_CriarTabelasReceitas")]
    partial class CriarTabelasReceitas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IngredienteRestricaoAlimentar", b =>
                {
                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RestricoesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IngredienteId", "RestricoesId");

                    b.HasIndex("RestricoesId");

                    b.ToTable("IngredienteRestricoes", (string)null);
                });

            modelBuilder.Entity("PerfilAlimentarRestricaoAlimentar", b =>
                {
                    b.Property<Guid>("PerfilAlimentarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RestricoesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PerfilAlimentarId", "RestricoesId");

                    b.HasIndex("RestricoesId");

                    b.ToTable("PerfilAlimentarRestricoes", (string)null);
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.IngredienteReceita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReceitaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("IngredientesReceita");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PassoPreparo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceitaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("PassosPreparo");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PerfilAlimentar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PerfisAlimentares");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porcoes")
                        .HasColumnType("int");

                    b.Property<int>("TempoMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.RestricaoAlimentar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RestricoesAlimentares");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Descricao = "Trigo, cevada, centeio e derivados",
                            Nome = "Glúten"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Descricao = "Leite e derivados",
                            Nome = "Lactose"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Descricao = "Ovos e derivados",
                            Nome = "Ovo"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Descricao = "Soja e derivados",
                            Nome = "Soja"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Descricao = "Amendoim e derivados",
                            Nome = "Amendoim"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Descricao = "Castanhas, nozes e similares",
                            Nome = "Nozes e castanhas"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Descricao = "Peixes e frutos do mar",
                            Nome = "Frutos do mar"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Descricao = "Boi, porco e derivados",
                            Nome = "Carne vermelha"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Descricao = "Sem produtos de origem animal",
                            Nome = "Vegano"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Descricao = "Sem carne, mas pode conter derivados animais",
                            Nome = "Vegetariano"
                        });
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IngredienteRestricaoAlimentar", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restrichef.Api.Domain.Entities.RestricaoAlimentar", null)
                        .WithMany()
                        .HasForeignKey("RestricoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfilAlimentarRestricaoAlimentar", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.PerfilAlimentar", null)
                        .WithMany()
                        .HasForeignKey("PerfilAlimentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restrichef.Api.Domain.Entities.RestricaoAlimentar", null)
                        .WithMany()
                        .HasForeignKey("RestricoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.IngredienteReceita", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restrichef.Api.Domain.Entities.Receita", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PassoPreparo", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.Receita", null)
                        .WithMany("PassosPreparo")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.PerfilAlimentar", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.User", null)
                        .WithOne("PerfilAlimentar")
                        .HasForeignKey("Restrichef.Api.Domain.Entities.PerfilAlimentar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Receita", b =>
                {
                    b.HasOne("Restrichef.Api.Domain.Entities.Ingrediente", null)
                        .WithMany("Receitas")
                        .HasForeignKey("IngredienteId");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Ingrediente", b =>
                {
                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.Receita", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("PassosPreparo");
                });

            modelBuilder.Entity("Restrichef.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("PerfilAlimentar")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
